src/MusicStore.Spa/Controllers/PageController.cs
using System.Security.Claims;
using Microsoft.AspNet.Mvc;

namespace MusicStore.Spa.Controllers
{
    [Route("/")]
    public class PageController : Controller
    {
        [HttpGet]
        public IActionResult Home()
        {
            return View("/Pages/Home.cshtml");
        }

        [HttpGet("admin")]
        [Authorize("app-ManageStore", "Allowed")]
        public IActionResult Admin()
        {
            return View("/Pages/Admin.cshtml");
        }
    }
}

src/MusicStore.Spa/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="@ViewBag.ngApp" data-url-base="@Url.Content("~/")">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – MVC Music Store</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/respond/respond.src.js"></script>
    <script src="~/lib/modernizr/modernizr.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ASP.NET MVC Music Store", "Home", "Page", null, new { @class = "navbar-brand" })
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Home", "Page")</li>
                    
                    @RenderSection("NavBarItems", required: false)

                    @*@Html.Action("CartSummary", "ShoppingCart")*@
                </ul>
                @(await Html.PartialAsync("_LoginPartial"))
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="navbar navbar-fixed-bottom navbar-default text-center">
            <p><a href="https://github.com/aspnet/musicstore">github.com/aspnet/musicstore</a></p>
            <small>@Html.ActionLink("admin", "Admin", "Page")</small>
        </footer>
    </div>

    @* TODO: Need to figure out best way to switch these to min links for release, e.g. new helper,
        Grunt task to replace, CDN support, etc. *@
    <script src="~/lib/jquery/jquery.js"></script>
    @*<script src="~/lib/jquery.validation/jquery.validate.js"></script>*@
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>